version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-1-11-18-2022-4
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
- name: client1
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-1-11-18-2022-4
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
- name: client2
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-1-11-18-2022-4
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
secrets:
- name: ACTIVATION_KEY
