version: '3'
virtualmachines:
- environment:
    TERM: xterm
  image: pprojects/tmm-instruqt-11-26-2021/global/images/rhel-9-2-6-20-23
  machine_type: n1-standard-1
  name: rhel
  shell: /bin/bash
secrets:
- name: ACTIVATION_KEY