version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-4-09-28-2022-v2
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
secrets:
- name: ACTIVATION_KEY